before_script:
  - apt-get update && apt-get install -y qt4-dev-tools libqtwebkit-dev libasound2-dev liblog4cpp5-dev cmake
  - git clone http://192.168.0.9:8086/git/aero-node/JThread.git && \
    cd JThread && mkdir build && cd build && cmake ..  && \
    make && sudo make install && cd ..
  - git clone http://192.168.0.9:8086/git/aero-node/JRTPLIB.git && \
    cd JRTPLIB && mkdir build && cd build && cmake ..  && \
    make && sudo make install && cd ..
  - git clone http://192.168.0.9:8086/git/aero-node/bcg729.git && \
    cd bcg729 && mkdir build && cd build && cmake ..  && \
    make && sudo make install && cd ..

aero-node:
  script:
    - mkdir build && cd build
    - cmake ..
    - make

# aero-node-crosscompile:
#     - 