image: 192.168.0.9:5000/aeronode-ci:0.1

aero-node:
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - make doc

aero-node-debug:
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make

aero-node-Tiny4412:
  script:
    - export PATH=/opt/FriendlyARM/toolschain/4.5.1/bin:$PATH
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TARGET=Tiny4412 \
      -DCMAKE_BUILD_TYPE=Debug ..
    - make