FROM ubuntu:16.04

COPY sources.list /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y \
    git \
    g++ \
    gcc \
    cmake \
    python-dev \
    python3-dev \
    doxygen \
    wget \
    lib32z1 \
    swig3.0 \
    libqt4-dev \
    libqtwebkit-dev \
    libasound2-dev \
    liblog4cpp5-dev \
    sudo \
    graphviz \
    && apt-get clean