#!/bin/sh
################################################################################
# 
# Copyright (c) 2018 NUAA AeroLab
# 
# @author   Jiang Yang (j824544269@gmail.com)
# @date     2017-12
# @brief    @TODO Let aero-node run as service.
# @version  0.0.1
# 
# Last Modified:  2018-09-06
# Modified By:    Jiang Yang (j824544269@gmail.com)
# 
################################################################################

base=aero-node

# See how we were called.
case "$1" in
    start)
        cd /home/aero-node
        /bin/an-run ./${base} &
        ;;
    stop)
        pid=`/bin/pidof ${base}`
        if [ -n "${pid}" ]; then
            kill -9 ${pid}
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    reload)
        ;;
    status)
        ;;
    *)
        exit 2
        ;;
esac

exit 0