#!/bin/sh
################################################################################
# 
# Copyright (c) 2018 南京航空航天大学 航空通信网络研究室
# 
# @author   姜阳 (j824544269@gmail.com)
# @date     2017-12
# @brief    
# @version  0.0.1
# 
# Last Modified:  2018-01-04
# Modified By:    姜阳 (j824544269@gmail.com)
# 
################################################################################

# echo "Enter Qt program path : "
# read PROGRAM

. /bin/setqt4env

export LOGNAME=root
export LD_LIBRARY_PATH=/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib:$LD_LIBRARY_PATH

hotplug

$1 -qws